SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
SHOT_RADIUS = 5
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

# Game improvements
PLAYER_LIVES = 3
INVINCIBILITY_SECONDS = 2.0
ASTEROID_POINTS_SMALL = 25
ASTEROID_POINTS_MEDIUM = 50
ASTEROID_POINTS_LARGE = 100
SHOT_LIFETIME_SECONDS = 2.0
HIGH_SCORE_FILE = "highscore.json"
STAR_COUNT = 100
EXPLOSION_PARTICLES = 12
